name: Build and Deploy Book

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_cran("bookdown")'
      
      - name: Build the book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
